### ISSUE TITLE
一个标签内部上下间距

### ISSUE THREAD

**Issue by BaanX** [huangxuan518/HXTagsView#10]
您好,感谢提供框架!
使用中遇到问题想咨询下.
@property (nonatomic,assign) CGFloat tagSpace;//标签内部左右间距(标题距离边框2边的距离和)
这个属性可以设置一个标签内部的左右间距,请问上下间距该如何设置呢

**Comment by huangxuan518** [comment]
@lipengda  设置标签高度即可，比如你需要上下间距为10，字体大小为14，则标签高度为10 + 14 + 10 = 34,设置self.tagsView.layout.itemSize.height = 34,layout为HXTagCollectionViewFlowLayout，初始高度为34
