### ISSUE TITLE
单选

### ISSUE THREAD

**Issue by winterrain5** [huangxuan518/HXTagsView#14]
cell加载HXTagsView,当多行时怎么保证只选择一个，也就是说整个tableView只有一个标签是选中状态，麻烦指教，谢谢

**Comment by huangxuan518** [comment]
@winterrain5  isMultiSelect设为NO，默认就是单选

**Comment by winterrain5** [comment]
只对单行cell起作用，其他行cell仍然还可以选择，谢谢 我再研究一下
