### ISSUE TITLE
标签数组若有重复元素，不能正常显示

### ISSUE THREAD

**Issue by JunL90s** [huangxuan518/HXTagsView#2]
你好，在使用过程中发现多行平铺，tags数组如果有相同的元素，tagsView不能显示出来。另外使用多个tagsView和其他多控件，布局结合Masonry使用发现tagsView的位置不能很好控制。

**Comment by huangxuan518** [comment]
@JunL90s  相同标签布局混乱的情况已经解决了,那是因为遍历数组的时候,因为元素一样,导致位置永远取的第一个的原因,现在已经解决了,至于你说的位置不太好控制,我不知道具体效果是需要怎样,你可以仔细看下说明文档,该控件完全可以支持一个项目多个地方使用
